name: Test
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - master

jobs:
  catkin-build:
    name: IDK
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: betwo/github-setup-catkin@master
      with:
        ros-version: 'melodic'
        build-tool: 'catkin_tools'
        workspace: '$GITHUB_WORKSPACE'
    - run: | 
        catkin build
        roslaunch example test.launch
