name: Test
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - master
      - test-new

jobs:
  catkin-build:
    name: IDK
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: betwo/github-setup-catkin@master
      with:
        ros-version: 'melodic'
        build-tool: 'catkin_tools'
        workspace: $GITHUB_WORKSPACE
    - run: |
        cd venne
        mkdir src 
        mv example src
        catkin build
        source devel/setup.bash
        roslaunch example test.launch
        
    #- run: source devel/setup.bash
    #- run: roslaunch example test.launch
    
