name: Test
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - master

jobs:
  ament_lint_cpp:
    name: IDK
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        path: ./cpp_template_pkg
    - uses: betwo/github-setup-catkin@master
      with:
        ros-version: 'melodic'
        build-tool: 'catkin_tools'
        workspace: cpp_template_pkg
    - run: catkin build
