name: Test
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - master
      - test-new

jobs:
  catkin-build:
    name: IDK
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: GuillaumeFalourd/clone-github-repo-action@v2
      with: 
        owner: 'Stenmarken'
        repository: 'test-action-ros-ci'
        access-token: ${{ secrets.ACCESS_TOKEN }}
        
    #- run: source devel/setup.bash
    #- run: roslaunch example test.launch
    
