name: Test
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - master

jobs:
  # Note that we pass each job a different name to distinguish each linter job
  ament_lint_cpp:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        linter: [cppcheck, xmllint]
    steps:
      - uses: ros-tooling/setup-ros@v0.3
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: my_package
          target-ros1-distro: melodic
